services:
   database-testing:
    image: mariadb:${MARIADB_VERSION:-latest}
    container_name: stormannsgal-mariadb
    ports:
      - "${MYSQL_PUBLIC_PORT:-3306}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-db}
      MYSQL_USER: ${MYSQL_USER:-dev}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-dev}
    volumes:
      - db-testing:/var/lib/mysql

volumes:
  db-testing:
